# Generated by Django 4.2.4 on 2023-08-31 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_topics_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('edited', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('title', models.CharField()),
                ('reaction', models.CharField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum_topics_app.forumtopics')),
            ],
        ),
    ]
