# Generated by Django 4.2.4 on 2023-08-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('edited', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
            ],
        ),
    ]
