# Generated by Django 4.2.4 on 2023-09-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_posts_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_by',
        ),
    ]
