# Generated by Django 4.2.4 on 2023-08-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='reaction',
        ),
        migrations.AddField(
            model_name='posts',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
