# Generated by Django 4.2.4 on 2023-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_posts_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='down',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='up',
            field=models.TextField(default=[]),
        ),
    ]
