# Generated by Django 4.2.4 on 2023-09-07 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_alter_posts_down_alter_posts_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='down',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='posts',
            name='up',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
