# Generated by Django 4.2.4 on 2023-09-12 15:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255)),
                ('edited', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('up', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list, size=None)),
                ('down', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list, size=None)),
            ],
        ),
    ]
