# Generated by Django 4.2.4 on 2023-08-31 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments_app', '0001_initial'),
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts_app.posts'),
        ),
    ]
