# Generated by Django 4.2.4 on 2023-09-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://api.multiavatar.com/User 1.png', max_length=255),
            preserve_default=False,
        ),
    ]
